[build-system]
build-backend = "flit_core.buildapi"
requires = [
  "flit-core>=3.7.1,<4",
]

[project]
name = "upstage-des"
version = "1.0.0"
description = "A library for behavior-driven discrete event simulation."
readme = "README.md"
keywords = [
  "agent based modeling",
  "agents",
  "behavior modeling",
  "discrete event simulation",
  "modeling",
  "operations",
  "simpy",
  "simulation",
]
license = { file = "LICENSE" }
authors = [
  { name = "James Arruda", email = "James.Arruda@gtri.gatech.edu" },
]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
  "simpy>=4",
]
optional-dependencies.docs = [
  "myst-parser",
  "pydata-sphinx-theme",
  "sphinx>=7",
]
optional-dependencies.lint = [
  "mypy",
  "pyproject-fmt>=2.5",
  "ruff>=0.6",
  "ssort>=0.12",
]
optional-dependencies.test = [
  "pytest",
  "pytest-cov",
  "pytest-html",
  "pytest-json-report",
  "pytest-xdist",
]
urls."Bug Tracker" = "https://github.com/gtri/upstage/issues"
urls.Documentation = "https://gtri.github.io/upstage"
urls.Source = "https://github.com/gtri/upstage"

[tool.flit]
sdist.exclude = [
  ".gitignore",
]

[tool.ruff]
line-length = 100
cache-dir = "build/.ruff_cache"
format.docstring-code-line-length = 100
lint.select = [
  "D",
  "E",
  "F",
  "I",
  "PLE",
  "PLW",
  "UP",
]
lint.ignore = [
  "D105",
]
lint.per-file-ignores."tests/__*.py" = [
  "D",
]
lint.per-file-ignores."tests/test*.py" = [
  "D",
]
lint.pydocstyle.convention = "google"

[tool.mypy]
# broken by ipywidgetsplugins = "pydantic.mypy"
cache_dir = "build/.mypy_cache"
sqlite_cache = true
python_version = "3.12"
allow_redefinition = true
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true
disable_error_code = "type-abstract"
overrides = [
  { module = [
    "importlib.metadata",
  ], ignore_missing_imports = true },
]

[tool.pytest]
ini_options.junit_family = "xunit2"
ini_options.cache_dir = "build/.pytest_cache"
ini_options.testpaths = [ "tests/" ]
ini_options.addopts = [
  # for contributors
  "--cov-report=term-missing:skip-covered",
  "--color=yes",
  # for review
  "--html=build/reports/pytest.html",
  "--self-contained-html",
  "--cov-report=html:build/reports/htmlcov",
  "--cov-report=xml:build/reports/coverage.xml",
  "--cov-context=test",
  # coverage
  "--cov=upstage_des",
  "--no-cov-on-fail",
  # for robots
  "--junitxml=build/reports/pytest.xunit.xml",
  "--json-report",
  # misc
  "-vv",
  "--ff",
]

[tool.coverage]
run.data_file = "build/reports/.coverage"
run.omit = [
  "*/upstage_des/utils.py",
  "tests/test*.py",
]
paths.upstage_des = [
  "src/upstage_des",
  "*/src/upstage_des",
]
report.exclude_also = [
  "except LookupError",
  "except MotionAndDetectionError",
  "except RuntimeError",
  "except SimulationError",
  "except TypeError",
  "raise MotionAndDetectionError",
  "raise NotImplementedError*",
  "raise SimulationError*",
  "raise TypeError",
  "raise UpstageError*",
]
html.show_contexts = true
