name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          manifest-path: pixi.toml
          pixi-version: v0.41.0
          cache: true
      - run: pixi run -e py312 build_html_docs

  jlite:
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Checkout the library
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install the dependencies
        run: |
          python -m pip install -r jupyterlite/requirements.txt
      - name: Build the JupyterLite site
        run: |
          cp README.md jupyterlite/content
          jupyter lite build --contents jupyterlite/content --output-dir build/docs/demo
  
  deploy:
    runs-on: ubuntu-latest
    needs: jlite
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/
          force_orphan: true
