name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          manifest-path: pixi.toml
          pixi-version: v0.41.0
          cache: true
      - run: pixi run -e py312 build_html_docs
      - name: Build the JupyterLite site
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: pixi run -e py312 build_jl
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/
          force_orphan: true
