name: Lint

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [py312]
    steps:
     - uses: actions/checkout@v4
     - uses: prefix-dev/setup-pixi@v0.8.1
       with:
         environments: ${{ matrix.environment }}
         manifest-path: pixi.toml
         pixi-version: v0.39.0
         cache: true
         auth-host: prefix.dev
         auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
     - run: pixi run lint-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [py311, py312, py313]
    steps:
     - uses: actions/checkout@v4
     - uses: prefix-dev/setup-pixi@v0.8.1
       with:
         environments: ${{ matrix.environment }}
         manifest-path: pixi.toml
         pixi-version: v0.39.0
         cache: true
         auth-host: prefix.dev
         auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
     - run: pixi run test
